---
- name: install nginx web server package
  hosts: all
  gather_facts: true
  become: true
  become_user: root
  
  tasks:
    - name: nginx package task
      dnf:
        name: nginx
        
    - name: Print some facts
      debug:
        msg: The facts are selinux info {{ ansible_selinux }}
    
    - name: Print when OS is CentOS
      debug:
        msg: "Yay! This is {{ ansible_distribution }} !! "
      when: ansible_distribution == "CentOS"
...
