---
- name: Start and enable nginx for CentOS
  hosts: all
  
  tasks:
    - name: Start and enable nginx for CentOS
      service:
        name: nginx
        enabled: true
        state: started
      when: ansible_distribution == "CentOS"
...
